### ISSUE TITLE
Allow users to join new rooms

### ISSUE THREAD

**Issue by jjmark15** [jjmark15/noughts-and-crosses#8]
# Background
Users will be able to join new or existing rooms. These rooms will host games.
Users will try to join a room by making a websocket connection.

# Requirement
- [x] allow users to join new rooms
- [x] leave room if user disconnects
- [x] only allow one room to be joined per user

# Implementation
- see #7 for results of investigation into use of websockets
- user should connect to server via websocket connection

# Todo
- [x] use a bounded channel for the transmitter (clueless as to what value to use for now so pulling 10 out of the air)

# Resources
- [warp websockets eample](https://github.com/seanmonstar/warp/blob/master/examples/websockets_chat.rs)

**Comment by jjmark15** [comment]
Solution:
- create a new user client / notifier domain object
- implementation of this contains a map of user id to user transmitter
- this implementation is directly required by this filter and the filter handles adding users to the map
- adding a user to a room then becomes a matter of adding their ID to a list associated with a room
- this might lead to making user connection separate to joining a room (although requirements-wise they are linked atm so maybe not)
